table DIM_acceptance_status
	lineageTag: 3cb29f9e-1943-4c08-bcdf-424b636fff8f

	measure PremiereValeurStatus = "Reco. " & LOWER(FIRSTNONBLANK(DIM_acceptance_status[status], ""))
		lineageTag: 2cd89d2b-cdf5-4836-8795-5404d62c475c

	column status_brut
		dataType: int64
		formatString: 0
		lineageTag: a5648dc7-d1ad-43bf-a35f-58950841f429
		summarizeBy: none
		sourceColumn: status_brut

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 8fc76afa-7253-4dec-960a-60ecee4169ff
		summarizeBy: none
		sourceColumn: status
		sortByColumn: status_brut

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column status_eng
		dataType: string
		lineageTag: 51437916-cfb4-4676-ad76-cf1d709c370a
		summarizeBy: none
		sourceColumn: status_eng
		sortByColumn: status_brut

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition DIM_acceptance_status = m
		mode: import
		queryGroup: dimension
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W0jVS0lEKSk0rLT68MlUhObG0OFWhtDgzLxUsnJWaXJKaoqARkJOYV6LgDJLVVIrVAWozxNTm6Yiix9ETWYMBUM41TyGxpCQ1rwRkeEBqXkpmXjpYEmSYY3JyakEJ0DQ4OzUFLAlyoGNBQU5mYSlUFsQBScYCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [status_brut = _t, status = _t, status_eng = _t]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"status_brut", Int64.Type}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

