table fact_parameter_tolerance
	lineageTag: 2a73bc9d-1c61-4bf3-9bfd-d03541661888

	measure Seuil_bas = ```
			
			VAR TypeParam = SELECTEDVALUE(dim_parameter_variable[type])
			RETURN
			SWITCH(
			    TypeParam,
			    "Temperature", (1 - ([Valeur Temperature] / 100)) * SUM(fact_parameter_tolerance[recommended_value]),
			    "Duration", (1 - ([Valeur Duration] / 100)) * SUM(fact_parameter_tolerance[recommended_value]),
			    "Count", (1 - ([Valeur Count] / 100)) * SUM(fact_parameter_tolerance[recommended_value]),
			    "Speed", (1 - ([Valeur Speed] / 100)) * SUM(fact_parameter_tolerance[recommended_value]),
			    BLANK()
			)
			
			```
		lineageTag: 543034d0-f883-439b-8f94-af49bc853d26

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Seuil_haut =
			
			VAR TypeParam = SELECTEDVALUE(dim_parameter_variable[type])
			RETURN
			SWITCH(
			    TypeParam,
			    "Temperature", (1 + ([Valeur Temperature] / 100)) * SUM(fact_parameter_tolerance[recommended_value]),
			    "Duration", (1 + ([Valeur Duration] / 100)) * SUM(fact_parameter_tolerance[recommended_value]),
			    "Count", (1 + ([Valeur Count] / 100)) * SUM(fact_parameter_tolerance[recommended_value]),
			    "Speed", (1 + ([Valeur Speed] / 100)) * SUM(fact_parameter_tolerance[recommended_value]),
			    BLANK()
			)
		lineageTag: 8b475f61-91f1-42fc-9464-dad81d3607f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Status tolerance V2' =
			
			VAR realizedValue = SUM(fact_parameter_tolerance[realized_value])
			RETURN IF(ISBLANK(realizedValue), BLANK(), IF(AND([Seuil_haut] >= realizedValue, [Seuil_bas] <= realizedValue), "Appliquée", "Non appliquée"))
		lineageTag: 8428a0b4-cd54-4bea-81d8-48f6f53d8384

	measure Status_Tolerance_Final = ```
			
			VAR NbTotal =
			    CALCULATE(
			        DISTINCTCOUNT(dim_parameter_variable[parameter_variable_label]),
			        ALLEXCEPT(fact_parameter_tolerance, fact_parameter_tolerance[id_recommendation])
			    )
			
			VAR NbApplique =
			    CALCULATE(
			        SUMX(
			            VALUES(dim_parameter_variable[parameter_variable_label]),
			            IF([Status tolerance V2] = "Appliquée", 1, 0)
			        ),
			        ALLEXCEPT(fact_parameter_tolerance, fact_parameter_tolerance[id_recommendation])
			    )
			
			RETURN
			IF(NbTotal = NbApplique, "Appliquée", "Non appliquée")
			
			```
		lineageTag: ecabcce3-2014-4359-bf92-239642138719

	measure Pourcentage_Applique = ```
			
			VAR NbIdTotal =
			    DISTINCTCOUNT(fact_parameter_tolerance[id_recommendation])
			
			VAR NbIdApplique =
			    CALCULATE(
			        DISTINCTCOUNT(fact_parameter_tolerance[id_recommendation]),
			        FILTER(
			            VALUES(fact_parameter_tolerance[id_recommendation]),
			            CALCULATE(
			                DISTINCTCOUNT(dim_parameter_variable[parameter_variable_label])
			            ) =
			            CALCULATE(
			                SUMX(
			                    VALUES(dim_parameter_variable[parameter_variable_label]),
			                    IF([Status tolerance V2] = "Appliquée", 1, 0)
			                )
			            )
			        )
			    )
			
			RETURN
			DIVIDE(NbIdApplique, NbIdTotal, 0)
			
			```
		lineageTag: 6ef9319a-8e18-4a43-bd6f-c7ff497dc2a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Pourcentage_non_applique = 1-[Pourcentage_Applique]
		lineageTag: e60d9f0b-b091-4f1b-960d-6e8b12a01a92

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Appliquée' = ```
			
			VAR TotalLignes = COUNTROWS('fact_parameter_tolerance')
			VAR TotalAppliquee = 
			    CALCULATE(
			        COUNTROWS('fact_parameter_tolerance'),
			        'fact_parameter_tolerance'[applied_status] = "Appliquée"
			    )
			RETURN
			DIVIDE(TotalAppliquee, TotalLignes, 0)
			```
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 8821be08-fcb4-4b29-a19b-c97659ca70f9

	column id_recommendation
		dataType: string
		lineageTag: 4af38b97-ed1b-4c2f-9c0b-3d77f1c67194
		summarizeBy: none
		sourceColumn: id_recommendation

		annotation SummarizationSetBy = Automatic

	column applied_status
		dataType: string
		lineageTag: 3e8f0ad1-aea8-44bc-ae30-9be2edbb4272
		summarizeBy: none
		sourceColumn: applied_status

		annotation SummarizationSetBy = Automatic

	column id_parameter_production_line
		dataType: string
		lineageTag: 92aafe34-f24d-43f1-a1a5-c9a79d61b287
		summarizeBy: none
		sourceColumn: id_parameter_production_line

		annotation SummarizationSetBy = Automatic

	column realized_value
		dataType: double
		lineageTag: 01b89264-3998-47ef-b690-859068737280
		summarizeBy: sum
		sourceColumn: realized_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tolerance
		dataType: double
		lineageTag: de70b261-242a-41c1-a6d8-79cb62303a7e
		summarizeBy: sum
		sourceColumn: tolerance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column upper_limit
		dataType: double
		lineageTag: d616bbcc-e31f-4bea-926a-4998224c1dc0
		summarizeBy: sum
		sourceColumn: upper_limit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lower_limit
		dataType: double
		lineageTag: 25d72ae5-176c-49b5-a15b-4ae1667cf176
		summarizeBy: sum
		sourceColumn: lower_limit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column applied_status_tolerance
		dataType: string
		lineageTag: d422a828-5638-4e74-8e20-f3492cf46527
		summarizeBy: none
		sourceColumn: applied_status_tolerance

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: de119671-53ef-4aa6-aa58-0d222adcdb9d
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: f9954e35-e386-4a3d-89e8-991c7917bb4c
			defaultHierarchy: LocalDateTable_49c80d9a-c28a-4cc5-927f-8d97d1a98845.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: d9bed08d-e0ec-4b9f-8d8c-47d6eb2ea1d4
		summarizeBy: none
		sourceColumn: updated_at

		variation Variation
			isDefault
			relationship: 502a4c70-3e23-4eb4-b1aa-9489052dfe6d
			defaultHierarchy: LocalDateTable_14f23b17-d850-4ad5-9f33-cf4537997939.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column deleted_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 4b56c215-8614-4653-81d7-2f02469a0d5d
		summarizeBy: none
		sourceColumn: deleted_at

		variation Variation
			isDefault
			relationship: fc586240-22b1-4d2d-96c1-e1c83de73833
			defaultHierarchy: LocalDateTable_43c23602-5d32-4737-bbf0-de846a5203b0.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column Status_Keep_Discard = ```
			
			IF(
			    ISBLANK(fact_parameter_tolerance[realized_value]) || 
			    TRIM(fact_parameter_tolerance[realized_value] & "") = "" || 
			    ISBLANK(fact_parameter_tolerance[recommended_value]) || 
			    TRIM(fact_parameter_tolerance[recommended_value] & "") = "", 
			    "Vide", 
			    "A garder"
			)
			
			```
		lineageTag: 9322ed06-6936-4c99-9b95-aa82a5dc10af
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column id_batch
		dataType: string
		lineageTag: 6431a439-70bf-42d0-a906-1c7bb8cd92ea
		summarizeBy: none
		sourceColumn: id_batch

		annotation SummarizationSetBy = Automatic

	column batch_number
		dataType: string
		lineageTag: 3e30fd66-ed11-44e6-9556-dc9caa55750c
		summarizeBy: none
		sourceColumn: batch_number

		annotation SummarizationSetBy = Automatic

	column delta_realized_predicted
		dataType: double
		lineageTag: 4eccb42d-7313-4180-b1c7-df330331fa79
		summarizeBy: sum
		sourceColumn: delta_realized_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column target_localization
		dataType: string
		lineageTag: 3cdd6489-695e-4e3e-8772-61da6a7b707f
		summarizeBy: none
		sourceColumn: target_localization

		annotation SummarizationSetBy = Automatic

	column recommended_value
		dataType: double
		lineageTag: 61f1abce-d2f3-4647-838f-5efe0ca8e0fa
		summarizeBy: sum
		sourceColumn: recommended_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_parameter_tolerance = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-6120597545375074.14.azuredatabricks.net", "/sql/1.0/warehouses/02983fe27612f7ca", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    mal_maite_bi_prd_Database = Source{[Name="mal_maite_bi_prd",Kind="Database"]}[Data],
				    parameters_Schema = mal_maite_bi_prd_Database{[Name="parameters",Kind="Schema"]}[Data],
				    fact_parameter_tolerance_Table = parameters_Schema{[Name="fact_parameter_tolerance",Kind="Table"]}[Data],
				    #"Requêtes fusionnées" = Table.NestedJoin(fact_parameter_tolerance_Table, {"id_batch"}, DIM_BATCH, {"id_batch"}, "DIM_BATCH", JoinKind.LeftOuter),
				    #"DIM_BATCH développé" = Table.ExpandTableColumn(#"Requêtes fusionnées", "DIM_BATCH", {"batch_number"}, {"batch_number"})
				in
				    #"DIM_BATCH développé"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

