table fact_process_time_analyses
	lineageTag: 8a8c0b71-c35f-47c2-a78e-2952aa2498de

	column batch_id
		dataType: string
		lineageTag: da12fbba-9e8c-4575-a1b5-83530a3fd753
		summarizeBy: none
		sourceColumn: batch_id

		annotation SummarizationSetBy = Automatic

	column mesure_name
		dataType: string
		lineageTag: 26f157b4-84ca-4794-91b0-3c3f5b264e8f
		summarizeBy: none
		sourceColumn: mesure_name

		annotation SummarizationSetBy = Automatic

	column mesure_value
		dataType: double
		lineageTag: 9580c92c-2138-43cc-b278-5711ae0b5fc3
		summarizeBy: sum
		sourceColumn: mesure_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column flg_top20_tonnage
		dataType: int64
		formatString: 0
		lineageTag: 7186f952-2889-43b1-a601-35b5fb9e010d
		summarizeBy: sum
		sourceColumn: flg_top20_tonnage

		annotation SummarizationSetBy = Automatic

	column top20_80th_percentile_tonnage
		dataType: double
		lineageTag: e59ee328-4c75-4770-9472-420c06e01c84
		summarizeBy: sum
		sourceColumn: top20_80th_percentile_tonnage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column delta_percentile_top_20_tonnage
		dataType: double
		lineageTag: 393bd929-cac5-4f96-9616-9bed825e9f64
		summarizeBy: sum
		sourceColumn: delta_percentile_top_20_tonnage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column categorie
		dataType: string
		lineageTag: 8418e630-775e-4b7b-967d-c791ebf29356
		summarizeBy: none
		sourceColumn: categorie

		annotation SummarizationSetBy = Automatic

	column measure_type
		dataType: string
		lineageTag: c3811ebf-830e-4f96-853a-b9b6cede60f6
		summarizeBy: none
		sourceColumn: measure_type

		annotation SummarizationSetBy = Automatic

	column sequence
		dataType: int64
		formatString: 0
		lineageTag: 75caf983-ec86-42e7-8819-f174f9f3c2bf
		summarizeBy: sum
		sourceColumn: sequence

		annotation SummarizationSetBy = Automatic

	column label
		dataType: string
		lineageTag: 24893365-cc12-4bcc-beca-7e1680bc858d
		summarizeBy: none
		sourceColumn: label

		annotation SummarizationSetBy = Automatic

	column measure_description
		dataType: string
		lineageTag: 0bf91fd8-5f6a-4f99-bf56-0e078f653e73
		summarizeBy: none
		sourceColumn: measure_description

		annotation SummarizationSetBy = Automatic

	column columns_source
		dataType: string
		lineageTag: cd3669e0-e34e-42ee-ac16-2cd4c9d58647
		summarizeBy: none
		sourceColumn: columns_source

		annotation SummarizationSetBy = Automatic

	column date_debut
		dataType: dateTime
		formatString: General Date
		lineageTag: 4046ebe6-0e39-4927-99ba-0431933cf979
		summarizeBy: none
		sourceColumn: date_debut

		annotation SummarizationSetBy = Automatic

	column date_fin
		dataType: dateTime
		formatString: General Date
		lineageTag: cead48e6-aadd-403e-8e12-1eb7b6ab663e
		summarizeBy: none
		sourceColumn: date_fin

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: e2e4dea2-dae3-498f-8380-4d30282a2ea5
		summarizeBy: none
		sourceColumn: created_at

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: c5ff20d0-81fd-4487-85b3-63b06c7f2a3b
		summarizeBy: none
		sourceColumn: updated_at

		annotation SummarizationSetBy = Automatic

	column deleted_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 24974cc1-8bbc-46d4-b45b-b81f7bc8df24
		summarizeBy: none
		sourceColumn: deleted_at

		annotation SummarizationSetBy = Automatic

	column measure_value_hhmm = ```
			
			VAR TotalMinutes = [mesure_value]
			VAR IsNegative = TotalMinutes < 0
			VAR AbsMinutes = ABS(TotalMinutes)
			VAR Heures = QUOTIENT(AbsMinutes, 60)
			VAR Minutes = INT(AbsMinutes) - Heures * 60
			VAR Result = FORMAT(Heures, "00") & ":" & FORMAT(Minutes, "00")
			RETURN
			IF(
			    ISBLANK(TotalMinutes),
			    BLANK(),
			    IF(IsNegative, "-" & Result, Result)
			)
			
			```
		displayFolder: ColonnesCalculees
		lineageTag: 554c61d9-a06c-4db1-ab20-18560a44e76c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column seuiltop20_value_hhmm = ```
			
			VAR TotalMinutes = [top20_80th_percentile_tonnage]
			VAR Heures = INT(TotalMinutes / 60)
			VAR Minutes = MOD(TotalMinutes, 60)
			RETURN
			IF(
			    ISBLANK(TotalMinutes),
			    BLANK(),
			    FORMAT(Heures, "00") & ":" & FORMAT(Minutes, "00")
			)
			
			```
		displayFolder: ColonnesCalculees
		lineageTag: 99aae162-87bb-4112-b28e-5429dafb4fb6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column deltatop20_value_hhmm = ```
			
			VAR TotalMinutes = [delta_percentile_top_20_tonnage]
			RETURN
			IF(
			    ISBLANK(TotalMinutes),
			    BLANK(),
			    VAR Sign = IF(TotalMinutes < 0, "-", "")
			    VAR AbsMinutes = ABS(TotalMinutes)
			    VAR Hours = INT(AbsMinutes / 60)
			    VAR MinutesRaw = AbsMinutes - Hours * 60
			    VAR Minutes = INT(ROUND(MinutesRaw, 0))
			    VAR AdjustedHours = IF(Minutes = 60, Hours + 1, Hours)
			    VAR AdjustedMinutes = IF(Minutes = 60, 0, Minutes)
			    RETURN
			        Sign & FORMAT(AdjustedHours, "00") & ":" & FORMAT(AdjustedMinutes, "00")
			)
			
			```
		displayFolder: ColonnesCalculees
		lineageTag: f81cc839-06cd-4743-8ac6-823f15ef3619
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column mesure_name_color =
			
			VAR MesureValue = CALCULATE(
			    MAX('fact_process_time_analyses'[mesure_value]),
			    ALLEXCEPT('fact_process_time_analyses', 'fact_process_time_analyses'[label], 'fact_process_time_analyses'[batch_id])
			)
			VAR TargetBusiness = CALCULATE(
			    MAX('fact_process_time_analyses'[target_business]),
			    ALLEXCEPT('fact_process_time_analyses', 'fact_process_time_analyses'[label], 'fact_process_time_analyses'[batch_id])
			)
			RETURN
			'fact_process_time_analyses'[label] &
			IF(
			    MesureValue > 0 && NOT(ISBLANK(TargetBusiness)),
			    IF(MesureValue > TargetBusiness, " (🔴)", " (🟢)"),
			    "(---)"  // Pas de pastille si valeur <= 0 OU pas d'objectif métier défini
			)
		displayFolder: ColonnesCalculees
		lineageTag: 0a80dd58-67be-4cd2-bca9-448889886aec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Last72hTransfert = ```
			
			IF(
			    'fact_process_time_analyses'[measure_type] = "Transfert" &&
			    TRUNC('fact_process_time_analyses'[date_fin]) >= TODAY() - 3 &&
			    TRUNC('fact_process_time_analyses'[date_fin]) <= TODAY(),
			    1,
			    0
			)
			
			```
		formatString: 0
		displayFolder: ColonnesCalculees
		lineageTag: 47931aeb-eed2-4a79-a056-11f34ef80e92
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Last72hattente = ```
			
			IF(
			    'fact_process_time_analyses'[measure_type] = "Attente" &&
			    TRUNC('fact_process_time_analyses'[date_fin]) >= TODAY() - 3 &&
			    TRUNC('fact_process_time_analyses'[date_fin]) <= TODAY(),
			    1,
			    0
			)
			
			```
		formatString: 0
		displayFolder: ColonnesCalculees
		lineageTag: fd4ef67e-9b2f-418f-a571-2a5eb3975927
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column mesure_value_h
		dataType: double
		lineageTag: eb86fcb5-9d5b-4be6-982f-cf2e46909b7e
		summarizeBy: sum
		sourceColumn: mesure_value_h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column top20_80th_percentile_h
		dataType: double
		lineageTag: 4b79e31a-c614-4787-8134-1134239078e3
		summarizeBy: sum
		sourceColumn: top20_80th_percentile_h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column delta_percentile_top_20_h
		dataType: double
		lineageTag: 321a78f9-8879-4fc0-8134-b01df51fbe5e
		summarizeBy: sum
		sourceColumn: delta_percentile_top_20_h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column week_mesure
		dataType: int64
		formatString: 0
		lineageTag: 01c58019-e466-4cf8-9526-bb18cf927d2a
		summarizeBy: sum
		sourceColumn: week_mesure

		annotation SummarizationSetBy = Automatic

	column year_mesure
		dataType: int64
		formatString: 0
		lineageTag: 246b0edb-5eeb-4b4f-a3a8-da3c885687c3
		summarizeBy: sum
		sourceColumn: year_mesure

		annotation SummarizationSetBy = Automatic

	column month_name_mesure
		dataType: string
		lineageTag: c54114b5-3485-4ab0-a6f3-e8a2fb63d7e4
		summarizeBy: none
		sourceColumn: month_name_mesure
		sortByColumn: month_num_mesure

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column flg_outlier
		dataType: int64
		formatString: 0
		lineageTag: 7ad23cfa-6c4c-4faa-a7b0-290e60278ac9
		summarizeBy: sum
		sourceColumn: flg_outlier

		annotation SummarizationSetBy = Automatic

	column Last72hcycles = ```
			
			IF(
			    'fact_process_time_analyses'[measure_type] = "BATCH_CYCLE_DURATION" &&
			    TRUNC('fact_process_time_analyses'[date_fin]) >= TODAY() - 3 &&
			    TRUNC('fact_process_time_analyses'[date_fin]) <= TODAY(),
			    1,
			    0
			)
			
			```
		formatString: 0
		displayFolder: ColonnesCalculees
		lineageTag: 5e411fa4-004a-4bd9-b282-21d97536a652
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Last72h_mesure =
			
			VAR NowFrance = MAX('dim_batches_specifications'[HeureFranceDynamique])
			
			RETURN
			IF(
			    'fact_process_time_analyses'[date_fin] >= NowFrance - 3
			        && 'fact_process_time_analyses'[date_fin] <= NowFrance,
			    1,
			    0
			)
		formatString: 0
		displayFolder: ColonnesCalculees
		lineageTag: be8b1456-3773-4952-8703-60145b31a865
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column month_num_mesure
		dataType: int64
		formatString: 0
		lineageTag: 10fd3510-6647-4661-b49a-82fc05d5ed07
		summarizeBy: sum
		sourceColumn: month_num_mesure

		annotation SummarizationSetBy = Automatic

	column target_business
		dataType: int64
		formatString: 0
		lineageTag: f80bcf8e-fd0c-4b75-87ae-3eb17995a3d1
		summarizeBy: sum
		sourceColumn: target_business

		annotation SummarizationSetBy = Automatic

	column delta_target_business
		dataType: double
		lineageTag: d3a4b91d-55ae-4c46-a9c8-c250b83c3703
		summarizeBy: sum
		sourceColumn: delta_target_business

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column delta_target_business_h
		dataType: double
		lineageTag: f69f322e-a15d-4338-b865-775a84b603e6
		summarizeBy: sum
		sourceColumn: delta_target_business_h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column target_business_h
		dataType: double
		lineageTag: 76f2cf28-36eb-4546-a705-a1817e39bccc
		summarizeBy: sum
		sourceColumn: target_business_h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column batch_prd_cell
		dataType: string
		lineageTag: c55a9d0b-09ff-4efd-a1af-2313a698732b
		summarizeBy: none
		sourceColumn: batch_prd_cell

		annotation SummarizationSetBy = Automatic

	column id_plant_production_line
		dataType: int64
		formatString: 0
		lineageTag: fe89ae39-7f62-4e54-9eeb-0bea50f672f9
		summarizeBy: none
		sourceColumn: id_plant_production_line

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b0b7301d-09d9-4e9b-a4da-453b060e1d82
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Last12s_measure = ```
			
			IF (
			    TRUNC(fact_process_time_analyses[date_fin]) >= TODAY() - 84
			    && TRUNC(fact_process_time_analyses[date_fin]) <= TODAY() - 0,
			    1,
			    0
			)
			
			```
		formatString: 0
		displayFolder: ColonnesCalculees
		lineageTag: bea862ab-34fa-4dc8-843e-b278830b6c78
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ColonneDateMoisTri = DATE([year_mesure],[month_num_mesure],1)
		formatString: General Date
		displayFolder: ColonnesCalculees
		lineageTag: ef6e4934-8cee-42da-a1a0-af91168be70e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Last10Days new' =
			
			
			IF(
			    'fact_process_time_analyses'[Date_fin_type_date] >= TODAY() - 10
			        && 'fact_process_time_analyses'[Date_fin_type_date] <= TODAY(),
			    "Last 10 Days",
			    "Other"
			)
		displayFolder: ColonnesCalculees
		lineageTag: 37cfa4ed-39ef-4477-ad7d-0f65dbc6b08e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Date_fin_type_date =
			
			DATE(
			    YEAR('fact_process_time_analyses'[date_fin]),
			    MONTH('fact_process_time_analyses'[date_fin]),
			    DAY('fact_process_time_analyses'[date_fin])
			)
		formatString: Short Date
		displayFolder: ColonnesCalculees
		lineageTag: c1506dcc-5964-44f7-bc81-06f92f02d82a
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column label_graphe_cycle_time
		dataType: string
		lineageTag: 9ca7c416-7394-4702-bf2b-845e8ddb4b14
		summarizeBy: none
		sourceColumn: label_graphe_cycle_time

		annotation SummarizationSetBy = Automatic

	column label_graphe_transfer_time
		dataType: string
		lineageTag: 060662e0-2a3e-4b9a-bd60-f3e6a5894b14
		summarizeBy: none
		sourceColumn: label_graphe_transfer_time

		annotation SummarizationSetBy = Automatic

	column label_graphe_waiting_time
		dataType: string
		lineageTag: 235b6e8f-1ad9-46ca-b262-b956ca6852ee
		summarizeBy: none
		sourceColumn: label_graphe_waiting_time

		annotation SummarizationSetBy = Automatic

	column mesure_value_transfer_graphe
		dataType: double
		lineageTag: 3354b18e-fa6f-484d-8902-02956161fdbb
		summarizeBy: sum
		sourceColumn: mesure_value_transfer_graphe

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mesure_value_waiting_graphe
		dataType: double
		lineageTag: a9077acf-5e91-47d2-8d11-15987dfcd570
		summarizeBy: sum
		sourceColumn: mesure_value_waiting_graphe

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column date_fin_tab_overwiew
		dataType: dateTime
		formatString: General Date
		lineageTag: cc7a7ff7-2d4b-4bd7-b078-4457f94baf93
		summarizeBy: none
		sourceColumn: date_fin_tab_overwiew

		annotation SummarizationSetBy = Automatic

	column columns_source_metadate
		dataType: string
		lineageTag: 0c5baef1-9fff-4bea-aa5d-59a52f1e1fd6
		summarizeBy: none
		sourceColumn: columns_source_metadate

		annotation SummarizationSetBy = Automatic

	column measure_type_matadata
		dataType: string
		lineageTag: 74aa52c5-3873-433e-b4d9-9b07f157edc5
		summarizeBy: none
		sourceColumn: measure_type_matadata

		annotation SummarizationSetBy = Automatic

	column 'label - CyTiWai'
		dataType: string
		lineageTag: 16e23eeb-2e2f-4e88-8c7b-b9fb7e911415
		summarizeBy: none
		sourceColumn: label - CyTiWai

		annotation SummarizationSetBy = Automatic

	column Last10DaysKeyTest =
			IF(
			    'fact_process_time_analyses'[Date_fin_type_date] >= TODAY() - 10
			        && 'fact_process_time_analyses'[Date_fin_type_date] <= TODAY(),
			    "LAST_10_DAYS",
			    "OTHER"
			)
		displayFolder: ColonnesCalculees
		lineageTag: dcd1515d-3fb9-4fe8-a8c1-d04d06a68edf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column targetbusiness_value_hhmm =
			
			VAR TotalMinutes = [target_business]
			VAR IsNegative = TotalMinutes < 0
			VAR AbsMinutes = ABS(TotalMinutes)
			VAR Heures = QUOTIENT(AbsMinutes, 60)
			VAR Minutes = INT(AbsMinutes) - Heures * 60
			VAR Result = FORMAT(Heures, "00") & ":" & FORMAT(Minutes, "00")
			RETURN
			IF(
			    ISBLANK(TotalMinutes),
			    BLANK(),
			    IF(IsNegative, "-" & Result, Result)
			)
		displayFolder: ColonnesCalculees
		lineageTag: 31f1e021-def2-4c64-bc54-4e2b9478a61f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column delta_targetbusiness_value_hhmm =
			
			VAR TotalMinutes = [delta_target_business]
			VAR IsNegative = TotalMinutes < 0
			VAR AbsMinutes = ABS(TotalMinutes)
			VAR Heures = QUOTIENT(AbsMinutes, 60)
			VAR Minutes = INT(AbsMinutes) - Heures * 60
			VAR Result = FORMAT(Heures, "00") & ":" & FORMAT(Minutes, "00")
			RETURN
			IF(
			    ISBLANK(TotalMinutes),
			    BLANK(),
			    IF(IsNegative, "-" & Result, Result)
			)
		displayFolder: ColonnesCalculees
		lineageTag: d90f4f4b-2ad5-4719-a72f-38819d762170
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fact_process_time_analyses = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-5761093891575298.18.azuredatabricks.net", "sql/protocolv1/o/5761093891575298/0612-144800-uikjvj67", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    mal_maite_bi_preprd_Database = Source{[Name="mal_maite_bi_preprd",Kind="Database"]}[Data],
				    process_time_analyses_Schema = mal_maite_bi_preprd_Database{[Name="process_time_analyses",Kind="Schema"]}[Data],
				    fact_process_time_analyses_Table = process_time_analyses_Schema{[Name="fact_process_time_analyses",Kind="Table"]}[Data],
				    #"Duplication de la colonne" = Table.DuplicateColumn(fact_process_time_analyses_Table, "label", "label - Copier"),
				    #"Colonnes renommées" = Table.RenameColumns(#"Duplication de la colonne",{{"label - Copier", "label_graphe_cycle_time"}}),
				    #"Duplication de la colonne1" = Table.DuplicateColumn(#"Colonnes renommées", "label_graphe_cycle_time", "label_graphe_cycle_time - Copier"),
				    #"Colonnes renommées1" = Table.RenameColumns(#"Duplication de la colonne1",{{"label_graphe_cycle_time - Copier", "label_graphe_transfer_time"}}),
				    #"Duplication de la colonne2" = Table.DuplicateColumn(#"Colonnes renommées1", "label_graphe_transfer_time", "label_graphe_transfer_time - Copier"),
				    #"Colonnes renommées2" = Table.RenameColumns(#"Duplication de la colonne2",{{"label_graphe_transfer_time - Copier", "label_graphe_waiting_time"}}),
				    #"Duplication de la colonne3" = Table.DuplicateColumn(#"Colonnes renommées2", "mesure_value_h", "mesure_value_h - Copier"),
				    #"Colonnes renommées3" = Table.RenameColumns(#"Duplication de la colonne3",{{"mesure_value_h - Copier", "mesure_value_transfer_graphe"}}),
				    #"Duplication de la colonne4" = Table.DuplicateColumn(#"Colonnes renommées3", "mesure_value_transfer_graphe", "mesure_value_transfer_graphe - Copier"),
				    #"Colonnes renommées4" = Table.RenameColumns(#"Duplication de la colonne4",{{"mesure_value_transfer_graphe - Copier", "mesure_value_waiting_graphe"}}),
				    #"Duplication de la colonne5" = Table.DuplicateColumn(#"Colonnes renommées4", "date_fin", "date_fin - Copier"),
				    #"Colonnes renommées5" = Table.RenameColumns(#"Duplication de la colonne5",{{"date_fin - Copier", "date_fin_tab_overwiew"}}),
				    #"Duplication de la colonne6" = Table.DuplicateColumn(#"Colonnes renommées5", "columns_source", "columns_source - Copier"),
				    #"Colonnes renommées6" = Table.RenameColumns(#"Duplication de la colonne6",{{"columns_source - Copier", "columns_source_metadate"}}),
				    #"Duplication de la colonne7" = Table.DuplicateColumn(#"Colonnes renommées6", "measure_type", "measure_type - Copier"),
				    #"Colonnes renommées7" = Table.RenameColumns(#"Duplication de la colonne7",{{"measure_type - Copier", "measure_type_matadata"}}),
				    #"Duplication de la colonne8" = Table.DuplicateColumn(#"Colonnes renommées7", "label", "label - Copier"),
				    #"Colonnes renommées8" = Table.RenameColumns(#"Duplication de la colonne8",{{"label - Copier", "label - CyTiWai"}})
				in
				    #"Colonnes renommées8"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

