table dim_specification
	lineageTag: 338931ba-f81a-4ff6-ba7f-5c9c1dca6da7

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: fd52d964-984f-4bf6-9d7e-6cc18327275e
		summarizeBy: none
		sourceColumn: created_at

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 9da612b9-ee89-4cb7-b105-d1963c5a13de
		summarizeBy: none
		sourceColumn: updated_at

		annotation SummarizationSetBy = Automatic

	column deleted_at
		dataType: dateTime
		formatString: General Date
		lineageTag: c1005ae6-f269-44ad-b662-d3395887515d
		summarizeBy: none
		sourceColumn: deleted_at

		annotation SummarizationSetBy = Automatic

	column id_cdc
		dataType: int64
		formatString: 0
		lineageTag: 9bb458b3-55c0-4077-b92e-3ed2768dd10b
		summarizeBy: none
		sourceColumn: id_cdc

		annotation SummarizationSetBy = Automatic

	column cdc
		dataType: string
		lineageTag: e6864440-b3ad-450a-b69b-6c97a9b96df3
		summarizeBy: none
		sourceColumn: cdc

		annotation SummarizationSetBy = Automatic

	partition dim_specification = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-5761093891575298.18.azuredatabricks.net", "sql/protocolv1/o/5761093891575298/0612-144800-uikjvj67", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    mal_maite_bi_preprd_Database = Source{[Name="mal_maite_bi_preprd",Kind="Database"]}[Data],
				    common_Schema = mal_maite_bi_preprd_Database{[Name="common",Kind="Schema"]}[Data],
				    dim_requirement_specification_Table = common_Schema{[Name="dim_requirement_specification",Kind="Table"]}[Data],
				    #"Colonnes conservees" = Table.SelectColumns(dim_requirement_specification_Table,
				        {"id_requirement_specification", "name", "created_at", "updated_at", "deleted_at"}),
				    #"Colonnes renommees" = Table.RenameColumns(#"Colonnes conservees",
				        {{"id_requirement_specification", "id_cdc"}, {"name", "cdc"}})
				in
				    #"Colonnes renommees"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

