table dim_batch
	lineageTag: 919d4d6a-bf1e-4290-b0e0-c798b731c8f2

	column id_batch
		dataType: string
		lineageTag: 371d07c9-9a81-43fa-bebc-84aaa898c922
		summarizeBy: none
		sourceColumn: id_batch

		annotation SummarizationSetBy = Automatic

	column batch_number
		dataType: string
		lineageTag: b24d638d-d0a5-4539-b59e-95ae2d7e2881
		summarizeBy: none
		sourceColumn: batch_number
		sortByColumn: debut_de_production

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ordre_fabrication
		dataType: string
		lineageTag: 77f14491-2a33-42d2-bd8f-1eeafdd3c9d3
		summarizeBy: none
		sourceColumn: ordre_fabrication

		annotation SummarizationSetBy = Automatic

	column annee_recolte
		dataType: int64
		formatString: 0
		lineageTag: de68590a-8361-4cff-bbd2-726d164e8d5e
		summarizeBy: sum
		sourceColumn: annee_recolte

		annotation SummarizationSetBy = Automatic

	column id_site
		dataType: int64
		formatString: 0
		lineageTag: b8d4ba35-758a-478f-9508-52acdf83942f
		summarizeBy: sum
		sourceColumn: id_site

		annotation SummarizationSetBy = Automatic

	column id_cdc
		dataType: int64
		formatString: 0
		lineageTag: 11af42f0-2b73-4749-8205-b4e9ea9ec27e
		summarizeBy: sum
		sourceColumn: id_cdc

		annotation SummarizationSetBy = Automatic

	column id_variete
		dataType: int64
		formatString: 0
		lineageTag: 2ae33aa3-46a1-4d71-b624-99911ff71b95
		summarizeBy: none
		sourceColumn: id_variete

		annotation SummarizationSetBy = Automatic

	column debut_de_production
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5ba25386-724c-46b1-8019-96fa2f5686ff
		summarizeBy: none
		sourceColumn: debut_de_production

		annotation SummarizationSetBy = Automatic

	column fin_de_production
		dataType: dateTime
		formatString: Short Date
		lineageTag: 922f845c-488d-4adf-b981-86d3e8573217
		summarizeBy: none
		sourceColumn: fin_de_production

		annotation SummarizationSetBy = Automatic

	column id_type
		dataType: int64
		formatString: 0
		lineageTag: 95e089c7-f4ee-4993-9def-2a095cfe7cc4
		summarizeBy: sum
		sourceColumn: id_type

		annotation SummarizationSetBy = Automatic

	column mes_number
		dataType: string
		lineageTag: 5c011ee9-38ac-4186-8b27-9365ddc6a040
		summarizeBy: none
		sourceColumn: mes_number

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 27cdbf60-e1d8-4625-8d02-1b5baf1aaccb
		summarizeBy: none
		sourceColumn: created_at

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 2f191936-35a3-49fe-8af3-10b53a3ca1bc
		summarizeBy: none
		sourceColumn: updated_at

		annotation SummarizationSetBy = Automatic

	column deleted_at
		dataType: dateTime
		formatString: General Date
		lineageTag: e37e5a94-b70d-45a7-ba02-5194d8ea95fc
		summarizeBy: none
		sourceColumn: deleted_at

		annotation SummarizationSetBy = Automatic

	column id_espece
		dataType: string
		lineageTag: 8b04f058-90eb-42cb-ad34-9f8967957c64
		summarizeBy: none
		sourceColumn: id_espece

		annotation SummarizationSetBy = Automatic

	partition dim_batch = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-5761093891575298.18.azuredatabricks.net", "sql/protocolv1/o/5761093891575298/0612-144800-uikjvj67", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    mal_maite_bi_preprd_Database = Source{[Name="mal_maite_bi_preprd",Kind="Database"]}[Data],
				    self_service_Schema = mal_maite_bi_preprd_Database{[Name="self_service",Kind="Schema"]}[Data],
				    dim_batch_Table = self_service_Schema{[Name="dim_batch",Kind="Table"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(dim_batch_Table,{{"ordre_fabrication", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

