table parameters_variables_translations
	lineageTag: 5c5a6473-8ba6-461a-8f09-48b07997f7de

	column parameter_variable
		dataType: int64
		formatString: 0
		lineageTag: 680bb896-f9d8-434f-8116-492f138a7f7c
		summarizeBy: none
		sourceColumn: parameter_variable

		annotation SummarizationSetBy = Automatic

	column language
		dataType: int64
		formatString: 0
		lineageTag: 2ae86061-4667-4bf6-a635-611dcf021027
		summarizeBy: sum
		sourceColumn: language

		annotation SummarizationSetBy = Automatic

	column label
		dataType: string
		lineageTag: 4ded5c2e-05f2-4a56-88f3-6534b6a20e6c
		summarizeBy: none
		sourceColumn: label

		annotation SummarizationSetBy = Automatic

	column deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ea79c5b6-f2ad-4f9b-b11b-41f0cfba2d99
		summarizeBy: none
		sourceColumn: deleted

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: db990fb8-3b8d-4a53-a92c-4a955e62ab8b
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: e99b916d-70e7-44a4-98ef-9419187c23d3
			defaultHierarchy: LocalDateTable_1c31f3bb-e91a-4d8d-93d6-ed84daa2081b.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 04bdc99c-5dbb-493d-b1d6-67c57af84b94
		summarizeBy: none
		sourceColumn: updated_at

		variation Variation
			isDefault
			relationship: 4a446a75-c342-499d-a2b9-0555f4ad7d12
			defaultHierarchy: LocalDateTable_d98f99aa-a826-4ffc-99d5-bdaa4180c916.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column deleted_at
		dataType: dateTime
		formatString: General Date
		lineageTag: d6ea96c3-e1b8-4dd0-ac93-ebc4d76ff85d
		summarizeBy: none
		sourceColumn: deleted_at

		variation Variation
			isDefault
			relationship: cde65637-7b1e-4a42-b0ad-1f0741114f00
			defaultHierarchy: LocalDateTable_d3a41267-1b3d-477e-b433-4eef606a5ddc.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: b4f52352-1119-4546-98e7-24ffa20fa780
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	partition parameters_variables_translations = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-6120597545375074.14.azuredatabricks.net", "/sql/1.0/warehouses/02983fe27612f7ca", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    ext_mal_psql_maite_vision_board_prd_Database = Source{[Name="ext_mal_psql_maite_vision_board_prd",Kind="Database"]}[Data],
				    public_Schema = ext_mal_psql_maite_vision_board_prd_Database{[Name="public",Kind="Schema"]}[Data],
				    parameters_variables_translations_Table = public_Schema{[Name="parameters_variables_translations",Kind="Table"]}[Data],
				    #"Lignes filtrées" = Table.SelectRows(parameters_variables_translations_Table, each ([language] = 1)),
				    #"Requêtes fusionnées" = Table.NestedJoin(#"Lignes filtrées", {"parameter_variable"}, parameters_variables, {"id_parameter_variable"}, "parameters_variables", JoinKind.LeftOuter),
				    #"parameters_variables développé" = Table.ExpandTableColumn(#"Requêtes fusionnées", "parameters_variables", {"code"}, {"code"})
				in
				    #"parameters_variables développé"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

